name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "30 1 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./Automation/IO/IOTests.sln
    - name: Build
      run: dotnet build ./Automation/IO/IOTests.sln --configuration Release --no-restore 
    - name: Test
      run: dotnet test ./Automation/IO/IOTests/bin/Release/netcoreapp3.1/IOTests.dll --no-build --verbosity normal
